/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-08-29 09:42:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class application_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>application</title>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("      <link href=\"https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("      <style>\r\n");
      out.write(" *{\r\n");
      out.write("margin: 0;\r\n");
      out.write("padding: 0;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#navId{\r\n");
      out.write("display: flex;\r\n");
      out.write("align-items: center;\r\n");
      out.write("}\r\n");
      out.write("#navId{\r\n");
      out.write("position: relative;\r\n");
      out.write("}\r\n");
      out.write("#pic{\r\n");
      out.write("margin: 10px 10px;\r\n");
      out.write("height: 60px;\r\n");
      out.write("}\r\n");
      out.write("#navId::before{\r\n");
      out.write(" content: \"\";\r\n");
      out.write(" background-color: gray;\r\n");
      out.write(" position: absolute;\r\n");
      out.write(" height: 100%;\r\n");
      out.write(" width: 100%;\r\n");
      out.write(" z-index: -1;\r\n");
      out.write(" opacity: 0.4;\r\n");
      out.write("}\r\n");
      out.write("#form{\r\n");
      out.write("    background-color: lightskyblue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <hr style=\"height: 2px;width: 90%;\"></hr>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Nav tabs -->\r\n");
      out.write("    <ul class=\"nav nav-pills\" id=\"navId\">\r\n");
      out.write("        <div id=\"pic\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index\">\r\n");
      out.write("          <img src=\"pic.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/leave\" class=\"nav-link\">Profile</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/application\" class=\"nav-link active\">Application</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("<!-- checking if user is Boss or not and displaying content on its basis -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/application.jsp(81,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.desig == 'Boss'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <li class=\"nav-item\">\r\n");
          out.write("        <a href=\"");
          out.print(request.getContextPath());
          out.write("/status?id=");
          out.print(request.getParameter("id"));
          out.write("\" class=\"nav-link\">Accept or Reject</a>\r\n");
          out.write("      </li>\r\n");
          out.write("      <li class=\"nav-item\">\r\n");
          out.write("        <a href=\"");
          out.print(request.getContextPath());
          out.write("/bonus?id=");
          out.print(request.getParameter("id"));
          out.write("\" class=\"nav-link\">Bonus leaves</a>\r\n");
          out.write("      </li>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index\" class=\"nav-link\">Logout</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("       \t<div class=\"container\"> \r\n");
      out.write("\t\t<div  class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12-12\">  \r\n");
      out.write("\t\t\t\t<h2 style=\"text-align: center;color: rgb(25, 19, 80);font-family: Georgia, 'Times New Roman', Times, serif;font-size: 30px;margin-top: 50px;;\">Leave Application </h2>\r\n");
      out.write("                        <br>\r\n");
      out.write("\t\t\t              \r\n");
      out.write("\t\t\t\t<form style=\"text-align: center;\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/application\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"user id\"style=\"text-decoration:bold;\">UserId</label><br>               \r\n");
      out.write("                    <input type=\"text\" name=\"id\" id=\"user id\" style=\"width:500px;height:0.5px;padding:15px;border-radius: 5px;background-color: rgb(142, 200, 218);color:  black;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"Department\"style=\"text-decoration:bold;\">Department</label><br>               \r\n");
      out.write("                    <input type=\"text\" name=\"dept\" id=\"user id\" style=\"width:500px;height:0.5px;padding:15px;border-radius: 5px;background-color: rgb(142, 200, 218);color:  black;\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"leave_type\"style=\"text-decoration:bold;\">leave type</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"leave_type\" id=\"user id\" style=\"width:500px;height:0.5px;padding:15px;border-radius: 5px;background-color: rgb(142, 200, 218);color:  black;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"leave reason\"style=\"text-decoration;\">sustitude</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"subs\" id=\"leave reason\" style=\"width:500px;height:0.5px;padding:15px;border-radius: 5px;background-color: rgb(142, 200, 218);color: black;\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"starting\"style=\"text-decoration:bold;\">Starting date of leave</label><br>\r\n");
      out.write("                    <input type=\"date\" name=\"from_date\" id=\"duration\" class=\"form-control\" style=\"width:500px;height:0.5px;padding:15px;border-radius: 5px;background-color: rgb(142, 200, 218);color: black;\">\r\n");
      out.write("                </div>           \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"ending\"style=\"text-decoration:bold;\">Ending date of leave</label><br>                   \r\n");
      out.write("                    <input type=\"date\" name=\"to_date\" id=\"ending\" class=\"form-control\" style=\"width:500px;height:0.5px;padding:15px;border-radius: 5px;background-color: rgb(142, 200, 218);color: black;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div> <input type=\"submit\" name=\"Submit\" style=\"border-radius: 20px;color:white;margin-left: 500px;width: 100px;height: 50px;background-color:rgb(28, 113, 224);\" value=\"Apply\">                \r\n");
      out.write("                <div> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${err}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/application.jsp(80,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("user");
    // /WEB-INF/views/application.jsp(80,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("session");
    // /WEB-INF/views/application.jsp(80,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/application.jsp(80,6) '${user}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${user}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
