/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-08-29 10:07:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;;

public final class application_005fstatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Connection connection;
	PreparedStatement statement,statement2;
	ResultSet result,result2;
	Class.forName("com.mysql.jdbc.Driver");
	connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/aios?serverTimezone=UTC","root","");
	
	statement = connection.prepareStatement("SELECT * FROM `leave_table` WHERE 1");
	result = statement.executeQuery();
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Leave Application Status</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css\" integrity=\"sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX\" crossorigin=\"anonymous\">\r\n");
      out.write("      <link href=\"https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css\" rel=\"stylesheet\"> \r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("#navId{\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("#navId{\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("#pic{\r\n");
      out.write("  margin: 10px 10px;\r\n");
      out.write("  height: 60px;\r\n");
      out.write("}\r\n");
      out.write("#navId::before{\r\n");
      out.write("   content: \"\";\r\n");
      out.write("   background-color: gray;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   z-index: -1;\r\n");
      out.write("   opacity: 0.4;\r\n");
      out.write("}\r\n");
      out.write(".row{\r\n");
      out.write("  margin-left: 80px;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".col-sm-3{\r\n");
      out.write("  margin-left: 40px;\r\n");
      out.write("  margin-top:20px;\r\n");
      out.write("  background-color: lightblue;\r\n");
      out.write("}\r\n");
      out.write(".card-body{\r\n");
      out.write("  background-color: rgb(221, 241, 182);\r\n");
      out.write("  font-family: 'Courier New', Courier, monospace;\r\n");
      out.write("}\r\n");
      out.write("h5{\r\n");
      out.write("  font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    </head> \r\n");
      out.write("    <hr style=\"height: 2px;width: 100%;\"></hr>\r\n");
      out.write("    <!-- Nav tabs -->\r\n");
      out.write("    <ul class=\"nav nav-pills\" id=\"navId\">\r\n");
      out.write("        <div id=\"pic\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index\">\r\n");
      out.write("          <img src=\"pic.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/leave\" class=\"nav-link\">Profile</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/application\" class=\"nav-link\">Application</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("<!-- checking if user is Boss or not and displaying content on its basis -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/application_status.jsp(86,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.desig == 'Boss'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <li class=\"nav-item\">\r\n");
          out.write("        <a href=\"");
          out.print(request.getContextPath());
          out.write("/status\" class=\"nav-link active\">Accept or Reject</a>\r\n");
          out.write("      </li>\r\n");
          out.write("      <li class=\"nav-item\">\r\n");
          out.write("        <a href=\"");
          out.print(request.getContextPath());
          out.write("/bonus\" class=\"nav-link\">Bonus leaves</a>\r\n");
          out.write("      </li>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index\" class=\"nav-link\">Logout</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\" style=\"padding: 1px;\">\r\n");
      out.write("    ");

    	while(result.next()){
    		String id=result.getString("empid");
    		String dept=result.getString("dept");
    		String lt=result.getString("leave_type");
    		String from=result.getString("from_date");
    		String to=result.getString("to_date");
    		String subs=result.getString("substitude");
    		String status=result.getString("status");
    		
    		if(status.equals("awaiting approval")){
    		
    
      out.write("\r\n");
      out.write("\t\t<div class=\"col-sm-3\">\r\n");
      out.write("        <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img src=\"https://www.clipartmax.com/png/middle/109-1092953_people-clipart-outing-people-white-vector-png.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Applicant Details</h5>\r\n");
      out.write("            <p class=\"card-text\">Name :");
 out.print(id);
      out.write("<br>\r\n");
      out.write("              Leave Type:");
 out.print(lt);
      out.write(" <br>\r\n");
      out.write("              Attendance: 9o%<br>\r\n");
      out.write("              Dept :");
 out.print(dept);
      out.write("<br>\r\n");
      out.write("              From :");
 out.print(from);
      out.write("<br>\r\n");
      out.write("              To :");
 out.print(to);
      out.write("<br>\r\n");
      out.write("              Working Days:200<br>\r\n");
      out.write("              Leaves Left:8<br>\r\n");
      out.write("              Substitute Recommended:<br>");
 out.print(subs);
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("            <a  href=\"accept.jsp?qid=");
      out.print(result.getString("id") );
      out.write("&id=");
      out.print(request.getParameter("id"));
      out.write("\" class=\"btn btn-primary\">Accept</a>\r\n");
      out.write("            <a  href=\"reject.jsp?qid=");
      out.print(result.getString("id") );
      out.write("&id=");
      out.print(request.getParameter("id"));
      out.write("\" class=\"btn btn-danger\">Reject</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    ");

    		}
   		}
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    <!-- Tab panes -->\r\n");
      out.write("    <div class=\"tab-content\">\r\n");
      out.write("      <div class=\"tab-pane fade show active\" id=\"tab1Id\" role=\"tabpanel\"></div>\r\n");
      out.write("      <div class=\"tab-pane fade\" id=\"tab2Id\" role=\"tabpanel\"></div>\r\n");
      out.write("      <div class=\"tab-pane fade\" id=\"tab3Id\" role=\"tabpanel\"></div>\r\n");
      out.write("      <div class=\"tab-pane fade\" id=\"tab4Id\" role=\"tabpanel\"></div>\r\n");
      out.write("      <div class=\"tab-pane fade\" id=\"tab5Id\" role=\"tabpanel\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("      $('#navId a').click(e => {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        $(this).tab('show');\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- all required inputs -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js\" integrity=\"sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/application_status.jsp(85,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("user");
    // /WEB-INF/views/application_status.jsp(85,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("session");
    // /WEB-INF/views/application_status.jsp(85,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/application_status.jsp(85,6) '${user}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${user}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
