/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-08-08 06:42:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <link href=\"https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <title>all in one security</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <header class=\"text-gray-700 body-font\">\r\n");
      out.write("    <div class=\"container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center\">\r\n");
      out.write("      <a class=\"flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\"\r\n");
      out.write("          stroke-linejoin=\"round\" stroke-width=\"2\" class=\"w-10 h-10 text-white p-2 bg-indigo-500 rounded-full\"\r\n");
      out.write("          viewBox=\"0 0 24 24\">\r\n");
      out.write("          <path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"></path>\r\n");
      out.write("        </svg>\r\n");
      out.write("        <span class=\"ml-3 text-xl\">All In One Security</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <nav class=\"md:ml-auto flex flex-wrap items-center text-base justify-center\">\r\n");
      out.write("        <a class=\"mr-5 hover:text-gray-900\">Home</a>\r\n");
      out.write("        <a class=\"mr-5 hover:text-gray-900\">About</a>\r\n");
      out.write("        <a class=\"mr-5 hover:text-gray-900\">Service</a>\r\n");
      out.write("        <a class=\"mr-5 hover:text-gray-900\">Contact</a>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <form action=\"");
      out.print(request.getContextPath() );
      out.write("/login\">\r\n");
      out.write("      <button\r\n");
      out.write("        class=\"inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0\">LOGIN\r\n");
      out.write("        </form>\r\n");
      out.write("        <svg fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("          class=\"w-4 h-4 ml-1\" viewBox=\"0 0 24 24\">\r\n");
      out.write("          <path d=\"M5 12h14M12 5l7 7-7 7\"></path>\r\n");
      out.write("        </svg>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <section class=\"text-gray-700 body-font\">\r\n");
      out.write("    <div class=\"container mx-auto flex px-5 py-24 md:flex-row flex-col items-center\">\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center\">\r\n");
      out.write("        <h1 class=\"title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900\">Always be safe with all in one\r\n");
      out.write("          security\r\n");
      out.write("          <br class=\"hidden lg:inline-block\">Get the best security solutions\r\n");
      out.write("        </h1>\r\n");
      out.write("        <p class=\"mb-8 leading-relaxed\">Providing expert security services across the Asia Pacific region, it is our\r\n");
      out.write("          mission to be our customers' best service provider.</p>\r\n");
      out.write("        <div class=\"flex justify-center\">\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg\">Learn\r\n");
      out.write("            more</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"lg:max-w-lg lg:w-full md:w-1/2 w-5/6\">\r\n");
      out.write("        <img class=\"object-cover object-center rounded\" alt=\"hero\"\r\n");
      out.write("          src=\"https://source.unsplash.com/700x600/? security camera\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <hr>\r\n");
      out.write("  <section class=\"text-gray-700 body-font\">\r\n");
      out.write("    <div class=\"container px-5 py-24 mx-auto\">\r\n");
      out.write("      <div class=\"text-center mb-20\">\r\n");
      out.write("        <h1 class=\"sm:text-3xl text-2xl font-medium text-center title-font text-gray-900 mb-4\">Find more</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"flex flex-wrap lg:w-4/5 sm:mx-auto sm:mb-2 -mx-2\">\r\n");
      out.write("        <div class=\"p-2 sm:w-1/2 w-full\">\r\n");
      out.write("          <div class=\"bg-gray-200 rounded flex p-4 h-full items-center\">\r\n");
      out.write("            <svg fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\"\r\n");
      out.write("              class=\"text-indigo-500 w-6 h-6 flex-shrink-0 mr-4\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path d=\"M22 11.08V12a10 10 0 11-5.93-9.14\"></path>\r\n");
      out.write("              <path d=\"M22 4L12 14.01l-3-3\"></path>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span class=\"title-font font-medium\">Global Account</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"p-2 sm:w-1/2 w-full\">\r\n");
      out.write("          <div class=\"bg-gray-200 rounded flex p-4 h-full items-center\">\r\n");
      out.write("            <svg fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\"\r\n");
      out.write("              class=\"text-indigo-500 w-6 h-6 flex-shrink-0 mr-4\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path d=\"M22 11.08V12a10 10 0 11-5.93-9.14\"></path>\r\n");
      out.write("              <path d=\"M22 4L12 14.01l-3-3\"></path>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span class=\"title-font font-medium\">Advanced Solution</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"p-2 sm:w-1/2 w-full\">\r\n");
      out.write("          <div class=\"bg-gray-200 rounded flex p-4 h-full items-center\">\r\n");
      out.write("            <svg fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\"\r\n");
      out.write("              class=\"text-indigo-500 w-6 h-6 flex-shrink-0 mr-4\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path d=\"M22 11.08V12a10 10 0 11-5.93-9.14\"></path>\r\n");
      out.write("              <path d=\"M22 4L12 14.01l-3-3\"></path>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span class=\"title-font font-medium\">Case studies</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"p-2 sm:w-1/2 w-full\">\r\n");
      out.write("          <div class=\"bg-gray-200 rounded flex p-4 h-full items-center\">\r\n");
      out.write("            <svg fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\"\r\n");
      out.write("              class=\"text-indigo-500 w-6 h-6 flex-shrink-0 mr-4\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path d=\"M22 11.08V12a10 10 0 11-5.93-9.14\"></path>\r\n");
      out.write("              <path d=\"M22 4L12 14.01l-3-3\"></path>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span class=\"title-font font-medium\">Join our team</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"p-2 sm:w-1/2 w-full\">\r\n");
      out.write("  </section>\r\n");
      out.write("  <hr>\r\n");
      out.write("  <section class=\"text-gray-700 body-font relative\">\r\n");
      out.write("    <div class=\"container px-5 py-24 mx-auto\">\r\n");
      out.write("      <div class=\"flex flex-col text-center w-full mb-12\">\r\n");
      out.write("        <h1 class=\"sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900\">Contact Us</h1>\r\n");
      out.write("        <p class=\"lg:w-2/3 mx-auto leading-relaxed text-base\">Whatever cardigan tote bag tumblr hexagon brooklyn\r\n");
      out.write("          asymmetrical gentrify.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"lg:w-1/2 md:w-2/3 mx-auto\">\r\n");
      out.write("        <div class=\"flex flex-wrap -m-2\">\r\n");
      out.write("          <div class=\"p-2 w-1/2\">\r\n");
      out.write("            <input\r\n");
      out.write("              class=\"w-full bg-gray-100 rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2\"\r\n");
      out.write("              placeholder=\"Name\" type=\"text\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"p-2 w-1/2\">\r\n");
      out.write("            <input\r\n");
      out.write("              class=\"w-full bg-gray-100 rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2\"\r\n");
      out.write("              placeholder=\"Email\" type=\"email\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"p-2 w-full\">\r\n");
      out.write("            <textarea\r\n");
      out.write("              class=\"w-full bg-gray-100 rounded border border-gray-400 focus:outline-none h-48 focus:border-indigo-500 text-base px-4 py-2 resize-none block\"\r\n");
      out.write("              placeholder=\"Message\"></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"p-2 w-full\">\r\n");
      out.write("            <button\r\n");
      out.write("              class=\"flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg\">Submit</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"p-2 w-full pt-8 mt-8 border-t border-gray-200 text-center\">\r\n");
      out.write("            <a class=\"text-indigo-500\">example@email.com</a>\r\n");
      out.write("            <p class=\"leading-normal my-5\">49 Smith St.\r\n");
      out.write("              <br>Saint Cloud, MN 56301\r\n");
      out.write("            </p>\r\n");
      out.write("            <span class=\"inline-flex\">\r\n");
      out.write("              <a class=\"text-gray-500\">\r\n");
      out.write("                <svg fill=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" class=\"w-5 h-5\"\r\n");
      out.write("                  viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <path d=\"M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"ml-4 text-gray-500\">\r\n");
      out.write("                <svg fill=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" class=\"w-5 h-5\"\r\n");
      out.write("                  viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z\">\r\n");
      out.write("                  </path>\r\n");
      out.write("                </svg>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"ml-4 text-gray-500\">\r\n");
      out.write("                <svg fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("                  class=\"w-5 h-5\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <rect width=\"20\" height=\"20\" x=\"2\" y=\"2\" rx=\"5\" ry=\"5\"></rect>\r\n");
      out.write("                  <path d=\"M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"ml-4 text-gray-500\">\r\n");
      out.write("                <svg fill=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" class=\"w-5 h-5\"\r\n");
      out.write("                  viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z\">\r\n");
      out.write("                  </path>\r\n");
      out.write("                </svg>\r\n");
      out.write("              </a>\r\n");
      out.write("            </span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
