/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-08-29 09:57:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.Aios.model.ApplicationModel;
import in.Aios.model.LoginModel;;

public final class leave_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <title>LEAVE PORTAL Profile Page</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    *{\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    #navId{\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("    #navId{\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    #pic{\r\n");
      out.write("      margin: 10px 10px;\r\n");
      out.write("      height: 60px;\r\n");
      out.write("    }\r\n");
      out.write("    #photo{\r\n");
      out.write("        margin: 50px 50px;\r\n");
      out.write("    }\r\n");
      out.write("    #navId::before{\r\n");
      out.write("       content: \"\";\r\n");
      out.write("       background-color: gray;\r\n");
      out.write("       position: absolute;\r\n");
      out.write("       height: 100%;\r\n");
      out.write("       width: 100%;\r\n");
      out.write("       z-index: -1;\r\n");
      out.write("       opacity: 0.4;\r\n");
      out.write("    }\r\n");
      out.write("    h2{\r\n");
      out.write("      margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    h4{\r\n");
      out.write("      margin-left: 40px;\r\n");
      out.write("    }\r\n");
      out.write("    h5{\r\n");
      out.write("      margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    @font-face {\r\n");
      out.write("  font-family: OpenSans-Regular;\r\n");
      out.write("  src: url('../fonts/OpenSans/OpenSans-Regular.ttf'); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0px; \r\n");
      out.write("\tpadding: 0px; \r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, html {\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\ttransition: all 0.4s;\r\n");
      out.write("\t-webkit-transition: all 0.4s;\r\n");
      out.write("  -o-transition: all 0.4s;\r\n");
      out.write("  -moz-transition: all 0.4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:focus {\r\n");
      out.write("\toutline: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {margin: 0px;}\r\n");
      out.write("\r\n");
      out.write("ul, li {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("  display: block;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tborder: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("  display: block;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea:focus, input:focus {\r\n");
      out.write("  border-color: transparent !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\toutline: none !important;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("iframe {\r\n");
      out.write("\tborder: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".limiter {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-table100 {\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  height: 300px;\r\n");
      out.write("  background: #c850c0;\r\n");
      out.write("  background: -webkit-linear-gradient(45deg, #4158d0, #c850c0);\r\n");
      out.write("  background: -o-linear-gradient(45deg, #4158d0, #c850c0);\r\n");
      out.write("  background: -moz-linear-gradient(45deg, #4158d0, #c850c0);\r\n");
      out.write("  background: linear-gradient(45deg, #4158d0, #c850c0);\r\n");
      out.write("\r\n");
      out.write("  display: -webkit-box;\r\n");
      out.write("  display: -webkit-flex;\r\n");
      out.write("  display: -moz-box;\r\n");
      out.write("  display: -ms-flexbox;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("  padding: 33px 30px;\r\n");
      out.write("  margin-left: 150px;\r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap-table100 {\r\n");
      out.write("  width: 1170px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("  border-spacing: 1;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  background: white;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("table * {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("table td, table th {\r\n");
      out.write("  padding-left: 8px;\r\n");
      out.write("}\r\n");
      out.write("table thead tr {\r\n");
      out.write("  height: 60px;\r\n");
      out.write("  background: #36304a;\r\n");
      out.write("}\r\n");
      out.write("table tbody tr {\r\n");
      out.write("  height: 50px;\r\n");
      out.write("}\r\n");
      out.write("table tbody tr:last-child {\r\n");
      out.write("  border: 0;\r\n");
      out.write("}\r\n");
      out.write("table td, table th {\r\n");
      out.write("  text-align: left;\r\n");
      out.write("}\r\n");
      out.write("table td.l, table th.l {\r\n");
      out.write("  text-align: right;\r\n");
      out.write("}\r\n");
      out.write("table td.c, table th.c {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("table td.r, table th.r {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".table100-head th{\r\n");
      out.write("  font-family: OpenSans-Regular;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  line-height: 1.2;\r\n");
      out.write("  font-weight: unset;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:nth-child(even) {\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr {\r\n");
      out.write("  font-family: OpenSans-Regular;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  color: #808080;\r\n");
      out.write("  line-height: 1.2;\r\n");
      out.write("  font-weight: unset;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:hover {\r\n");
      out.write("  color: #555555;\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column1 {\r\n");
      out.write("  width: 260px;\r\n");
      out.write("  padding-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column2 {\r\n");
      out.write("  width: 160px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column3 {\r\n");
      out.write("  width: 245px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column4 {\r\n");
      out.write("  width: 110px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 992px) {\r\n");
      out.write("  table {\r\n");
      out.write("    display: block;\r\n");
      out.write("  }\r\n");
      out.write("  table > *, table tr, table td, table th {\r\n");
      out.write("    display: block;\r\n");
      out.write("  }\r\n");
      out.write("  table thead {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("  table tbody tr {\r\n");
      out.write("    height: auto;\r\n");
      out.write("    padding: 37px 0;\r\n");
      out.write("  }\r\n");
      out.write("  table tbody tr td {\r\n");
      out.write("    padding-left: 40% !important;\r\n");
      out.write("    margin-bottom: 24px;\r\n");
      out.write("  }\r\n");
      out.write("  table tbody tr td:last-child {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("  }\r\n");
      out.write("  table tbody tr td:before {\r\n");
      out.write("    font-family: OpenSans-Regular;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #999999;\r\n");
      out.write("    line-height: 1.2;\r\n");
      out.write("    font-weight: unset;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 40%;\r\n");
      out.write("    left: 30px;\r\n");
      out.write("    top: 0;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  tbody tr {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 576px) {\r\n");
      out.write("  .container-table100 {\r\n");
      out.write("    padding-left: 15px;\r\n");
      out.write("    padding-right: 15px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Nav tabs -->\r\n");
      out.write("    <ul class=\"nav nav-pills\" id=\"navId\">\r\n");
      out.write("        <div id=\"pic\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index\">\r\n");
      out.write("          <img src=\"pic.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/leave\" class=\"nav-link active\">Profile</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/application\" class=\"nav-link\">Application</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("<!-- checking if user is Boss or not and displaying content on its basis -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/leave_profile.jsp(308,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.desig == 'Boss'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <li class=\"nav-item\">\r\n");
          out.write("        <a href=\"");
          out.print(request.getContextPath());
          out.write("/status\" class=\"nav-link\">Accept or Reject</a>\r\n");
          out.write("      </li>\r\n");
          out.write("      <li class=\"nav-item\">\r\n");
          out.write("        <a href=\"");
          out.print(request.getContextPath());
          out.write("/bonus\" class=\"nav-link\">Bonus leaves</a>\r\n");
          out.write("      </li>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index\" class=\"nav-link\">Logout</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("<!-- displaying personal info of user from user data -->  \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Personal Details</h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\" style=\"width:400px\">\r\n");
      out.write("          <div id=\"photo\">\r\n");
      out.write("            <img src=\"https://www.kindpng.com/picc/m/495-4952535_create-digital-profile-icon-blue-user-profile-icon.png\"\r\n");
      out.write("              width=\"200\" height=\"200\" >\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.surname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" </h4>\r\n");
      out.write("            <h5 class=\"card-text\"> Designation:Assistance Professor</h5>\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("        <div class=\"card w-75\">\r\n");
      out.write("        <div class=\"card bg-light text-dark\">\r\n");
      out.write("            <div class=\"card-body text-left\">\r\n");
      out.write("              <p class=\"card-text\">Employee ID:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.empid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<br>\r\n");
      out.write("                Contact no: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<br>\r\n");
      out.write("                Attendance: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.attendance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<br>\r\n");
      out.write("                Department :");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.dept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<br>\r\n");
      out.write("                Working Days:200<br>\r\n");
      out.write("                Leaves Left:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.days_left}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<br>\r\n");
      out.write("            </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- looping through leave data of user -->\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("          <div class=\"limiter\">\r\n");
      out.write("            <div class=\"container-table100\">\r\n");
      out.write("              <div class=\"wrap-table100\">\r\n");
      out.write("                <div class=\"table100\">\r\n");
      out.write("                  <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                      <tr class=\"table100-head\">\r\n");
      out.write("                        <th class=\"column1\">Types of Leaves</th>\r\n");
      out.write("                        <th class=\"column2\">Leaves Taken</th>\r\n");
      out.write("                        <th class=\"column3\">Total Leaves</th>\r\n");
      out.write("                        <th class=\"column4\">Leaves Left</th>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td class=\"column1\">Personal  Leaves</td>\r\n");
      out.write("                          <td class=\"column2\">3</td>\r\n");
      out.write("                          <td class=\"column3\">5</td>\r\n");
      out.write("                          <td class=\"column4\">2</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td class=\"column1\">Casual Leaves</td>\r\n");
      out.write("                          <td class=\"column2\">2</td>\r\n");
      out.write("                          <td class=\"column3\">4</td>\r\n");
      out.write("                          <td class=\"column4\">2</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td class=\"column1\">Sick Leaves</td>\r\n");
      out.write("                          <td class=\"column2\">3</td>\r\n");
      out.write("                          <td class=\"column3\">6</td>\r\n");
      out.write("                          <td class=\"column4\">3</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td class=\"column1\">Total</td>\r\n");
      out.write("                          <td class=\"column2\">8</td>\r\n");
      out.write("                          <td class=\"column3\">15</td>\r\n");
      out.write("                          <td class=\"column4\">7</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("           </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/leave_profile.jsp(307,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("user");
    // /WEB-INF/views/leave_profile.jsp(307,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("session");
    // /WEB-INF/views/leave_profile.jsp(307,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/leave_profile.jsp(307,6) '${user}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${user}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/leave_profile.jsp(356,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/leave_profile.jsp(356,0) '${leave_arr}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${leave_arr}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/leave_profile.jsp(356,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("data");
    // /WEB-INF/views/leave_profile.jsp(356,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("item");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("          <div class=\"card\" style=\"width: 18rem;\">\r\n");
          out.write("  \t\t\t<div class=\"card-body\">\r\n");
          out.write("\t   \t\t\t<h5 class=\"card-title\">Applied Leave </h5>\r\n");
          out.write("\t    \t\t<h6 class=\"card-subtitle mb-2 text-muted\"></h6>\r\n");
          out.write("\t\t\t    <p class=\"card-text\">Applied leave type:\r\n");
          out.write("\t\t\t    ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("<br>\r\n");
          out.write("\t\t\t    From:\r\n");
          out.write("\t\t\t    ");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("<br>\r\n");
          out.write("\t\t\t    to:\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("<br>\r\n");
          out.write("\t\t\t    Status : \r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t    </p>\r\n");
          out.write("\t\t\t    <a href=\"cancel.jsp?qid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("&id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.empid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"card-link\">Cancel</a>\r\n");
          out.write("\t\t\t   <!--  <a href=\"\" class=\"card-link\">update</a> -->\r\n");
          out.write("\t\t\t  </div>\r\n");
          out.write("\t\t\t</div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/leave_profile.jsp(363,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.leave_type}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/leave_profile.jsp(365,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.from_date}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/leave_profile.jsp(367,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.to_date}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/leave_profile.jsp(369,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.status}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }
}
